### ISSUE TITLE
VON Agent allows me to create multiple organizations with exactly the same attributes

### ISSUE THREAD

**Issue by mwherman2000** [bcgov/von-agent-template#26]
1. Create a new organization with http://ip172-18-0-72-bgabbbc3uhdg00fqct30-5001.direct.labs.play-with-docker.com/myorg/incorporation
2. Click Submit then OK multiple times.
3. Search bcgov: https://demo.orgbook.gov.bc.ca/en/search/name?query=Michael&page=1&issuer_id=&credential_type_id=&category:entity_type=&inactive=false

e.g. Michael Herman 2001 Corporation appears 3 times.

**Comment by jljordan42** [comment]
That’s not a big ... it is the issuers responsibility to care for the data quality. Presumably the registry service or permit service or whatever service is issuing would have the appropriate business logic. The agent is simply a tool to issue and verify credentials.  It does not have business logic in it.
