### ISSUE TITLE
Link to config guide is broken

### ISSUE THREAD

**Issue by fvllam** [bcgov/von-agent-template#46]
The root README.md has a link that points to `https://github.com/bcgov/von-agent-template/blob/master/von-x-agent/config/ConfigurationGuide.md` which doesn't exist.  I assume it should be pointing to `https://github.com/bcgov/von-agent-template/blob/master/von-x-agent/config/Readme.md`?

**Comment by swcurran** [comment]
@fvllam - thanks for the note.  Yup - set the name in the text but decided to name the file differently.  It is fixed now.

**Comment by secondtom** [comment]
Still broken, should be uppercase "README.md"

**Comment by swcurran** [comment]
Found that second reference and fixed it as well.  I think I've checked them all now....
