### ISSUE TITLE
Issues Running Locally with missing URL params and bad network config 

### ISSUE THREAD

**Issue by whatisthejava** [bcgov/von-agent-template#61]
Hey so a couple of issues if you pick number 2 in init.sh 

After starting manage start the following presents errors 

WARNING: The INDY_LEDGER_URL variable is not set. Defaulting to a blank string.
WARNING: The AUTO_REGISTER_DID variable is not set. Defaulting to a blank string.
WARNING: The INDY_GENESIS_URL variable is not set. Defaulting to a blank string.
WARNING: The ISSUER_WALLET_DID variable is not set. Defaulting to a blank string.

It then fails because the network tob_tob isnt created 

It tells you to create the docker network which is really useful.

You then run again and then you get then you get this error 

````
vonx.indy.errors.IndyConfigError: Neither INDY_GENESIS_URL nor INDY_LEDGER_URL are defined
````

You can get past this error by proving it on the runtime 

( Am running the VON network locally so my geneis url was http://localhost:9000/genesis

But then you get this error 
````
vonx.common.service.ServiceSyncError: Exception during fetching genesis transaction: Cannot connect to host localhost:9000 ssl:None [Cannot assign requested address] (None)
````
Cant get past this as the network defined wont let the docker containers connect to other servers running on my localmachine

**Comment by ianco** [comment]
Hi, from the errors it seems that the von-network and orgbook aren't running.  If you're running the "local machine" scenario make sure you start these services first, there are links to the instructions here:  https://github.com/bcgov/von-agent-template/blob/master/GettingStartedTutorial.md#local-machine-1
