### ISSUE TITLE
GreenLight Topography is stuck

### ISSUE THREAD

**Issue by whatisthejava** [bcgov/von-agent-template#62]
Hey so 
I downloaded the code 

ran init.sh and selected option 1 

The managed and built my services 

Following the readme I got to section 

### Step 4: Issuing a Credential Using GreenLight

And followerd the instruction and now my browser just spins when creating the topography 

https://greenlight.orgbook.gov.bc.ca/demo?name=saas.sass&version=1.0.0&did=J472BHBoR2g28przUB6eTt&issuer_endpoint=http:%2F%2F192.168.65.3:5001

Not sure what to do now ? , I presume its to do with the issuer_endpoint being 192 but again , dont see how to change that 

Any help would be great

**Comment by ianco** [comment]
For option 1 you should be running on Play With Docker (PWD)  (see https://github.com/bcgov/von-agent-template/blob/master/GettingStartedTutorial.md#in-browser), in which case the endpoint will be a PWD endpoint.

It looks like the endpoint is just your local IP, which will not be reachable from the BC Gov greenlight service.
